---

- host: false
  type: GET|POST
  pattern: "/"
  controller: Welcome::index

- host: false
  type: GET|POST
  pattern: "/login"
  controller: Auth::signin
  subsite: null

- host: false
  type: GET|POST
  pattern: "/register"
  controller: Auth::signup
  subsite: null
  
- host: false
  type: GET
  pattern: "/logout"
  controller: Auth::SessionLogout
  subsite: null
